### ISSUE TITLE
Site fails to load on Chrome

### ISSUE THREAD

**Issue by iconmaster5326** [stoz/dredmorpedia#1] opened 2017-06-08 02:31 UTC
On Chrome, attempting to load the page generates the following errors in the JS console:

```
Uncaught TypeError: Cannot read property 'Data' of undefined
    at craft.js?foible:228
craft.js?foible:170 Uncaught TypeError: Cannot read property 'statTypes' of undefined
    at Element.<anonymous> (craft.js?foible:170)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Element.<anonymous> (craft.js?foible:159)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.Dredmor.Craft.Parse (craft.js?foible:128)
    at Object.success (craft.js?foible:49)
    at Object.resolveWith (jquery.min.js:2)
    at w (jquery.min.js:4)
item.js?foible:794 Uncaught TypeError: Cannot read property 'ParseStats' of undefined
    at Object.Parse (item.js?foible:794)
    at Object.Parse (item.js?foible:760)
    at Object.Parse (item.js?foible:341)
    at Element.<anonymous> (item.js?foible:208)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.Dredmor.Item.Parse (item.js?foible:194)
    at Object.success (item.js?foible:65)
    at Object.resolveWith (jquery.min.js:2)
    at w (jquery.min.js:4)
item.js?foible:794 Uncaught TypeError: Cannot read property 'ParseStats' of undefined
    at Object.Parse (item.js?foible:794)
    at Object.Parse (item.js?foible:760)
    at Element.<anonymous> (item.js?foible:208)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.Dredmor.Item.Parse (item.js?foible:194)
    at Object.success (item.js?foible:65)
    at Object.resolveWith (jquery.min.js:2)
    at w (jquery.min.js:4)
    at XMLHttpRequest.d (jquery.min.js:4)
craft.js?foible:170 Uncaught TypeError: Cannot read property 'statTypes' of undefined
    at Element.<anonymous> (craft.js?foible:170)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Element.<anonymous> (craft.js?foible:159)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.Dredmor.Craft.Parse (craft.js?foible:128)
    at Object.success (craft.js?foible:49)
    at Object.resolveWith (jquery.min.js:2)
    at w (jquery.min.js:4)
item.js?foible:794 Uncaught TypeError: Cannot read property 'ParseStats' of undefined
    at Object.Parse (item.js?foible:794)
    at Object.Parse (item.js?foible:760)
    at Object.Parse (item.js?foible:477)
    at Element.<anonymous> (item.js?foible:208)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.Dredmor.Item.Parse (item.js?foible:194)
    at Object.success (item.js?foible:65)
    at Object.resolveWith (jquery.min.js:2)
    at w (jquery.min.js:4)
craft.js?foible:170 Uncaught TypeError: Cannot read property 'statTypes' of undefined
    at Element.<anonymous> (craft.js?foible:170)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Element.<anonymous> (craft.js?foible:159)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.Dredmor.Craft.Parse (craft.js?foible:128)
    at Object.success (craft.js?foible:49)
    at Object.resolveWith (jquery.min.js:2)
    at w (jquery.min.js:4)
skill.js?foible:176 Uncaught TypeError: Cannot read property 'ParseStats' of undefined
    at Element.<anonymous> (skill.js?foible:176)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.func (skill.js?foible:157)
    at Function.self.queueFunc (helper.js?foible:162)
    at helper.js?foible:203
craft.js?foible:170 Uncaught TypeError: Cannot read property 'statTypes' of undefined
    at Element.<anonymous> (craft.js?foible:170)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Element.<anonymous> (craft.js?foible:159)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.Dredmor.Craft.Parse (craft.js?foible:128)
    at Object.success (craft.js?foible:49)
    at Object.resolveWith (jquery.min.js:2)
    at w (jquery.min.js:4)
item.js?foible:794 Uncaught TypeError: Cannot read property 'ParseStats' of undefined
    at Object.Parse (item.js?foible:794)
    at Object.Parse (item.js?foible:489)
    at Element.<anonymous> (item.js?foible:208)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.Dredmor.Item.Parse (item.js?foible:194)
    at Object.success (item.js?foible:65)
    at Object.resolveWith (jquery.min.js:2)
    at w (jquery.min.js:4)
    at XMLHttpRequest.d (jquery.min.js:4)
monster.js?foible:215 Uncaught TypeError: Cannot read property 'ParseStats' of undefined
    at Object.Dredmor.Monster.ParseMonster (monster.js?foible:215)
    at Element.<anonymous> (monster.js?foible:141)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.Dredmor.Monster.Parse (monster.js?foible:136)
    at Object.success (monster.js?foible:64)
    at Object.resolveWith (jquery.min.js:2)
    at w (jquery.min.js:4)
    at XMLHttpRequest.d (jquery.min.js:4)
monster.js?foible:215 Uncaught TypeError: Cannot read property 'ParseStats' of undefined
    at Object.Dredmor.Monster.ParseMonster (monster.js?foible:215)
    at Element.<anonymous> (monster.js?foible:141)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.Dredmor.Monster.Parse (monster.js?foible:136)
    at Object.success (monster.js?foible:64)
    at Object.resolveWith (jquery.min.js:2)
    at w (jquery.min.js:4)
    at XMLHttpRequest.d (jquery.min.js:4)
monster.js?foible:215 Uncaught TypeError: Cannot read property 'ParseStats' of undefined
    at Object.Dredmor.Monster.ParseMonster (monster.js?foible:215)
    at Element.<anonymous> (monster.js?foible:141)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.Dredmor.Monster.Parse (monster.js?foible:136)
    at Object.success (monster.js?foible:64)
    at Object.resolveWith (jquery.min.js:2)
    at w (jquery.min.js:4)
    at XMLHttpRequest.d (jquery.min.js:4)
monster.js?foible:215 Uncaught TypeError: Cannot read property 'ParseStats' of undefined
    at Object.Dredmor.Monster.ParseMonster (monster.js?foible:215)
    at Element.<anonymous> (monster.js?foible:141)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.Dredmor.Monster.Parse (monster.js?foible:136)
    at Object.success (monster.js?foible:64)
    at Object.resolveWith (jquery.min.js:2)
    at w (jquery.min.js:4)
    at XMLHttpRequest.d (jquery.min.js:4)
```

I tested this on Chrome version 58.0.3029.110 (64-bit). It works fine for me on other browsers.

**Comment by stoz** [comment] 2017-06-08 04:05
I just tried myself on Chrome (was v58 but then Chrome updated itself to _Version 59.0.3071.86 (Official Build) (64-bit)_).

I didn't seem to have the problem you reported in either version. I'm on OS X, what operating system are you using?

**Comment by iconmaster5326** [comment] 2017-06-08 14:36
Interesting. I'm running it on Windows 10, myself.

**Comment by stoz** [comment] 2019-04-16 03:31
Thanks for the report. Someone else tracked it down and thinks the issue is to do with certain add blockers thinking that one of the dredmorpedia files (stat.js) is an advertising stats file.

The issue has been fixed by renaming the file from stats.js to dredmor-stats.js

I'll update the hosted website shortly.

**Closed as completed by stoz** 2019-04-16 03:31 UTC
